[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
skale_testnet = "${SKALE_TESTNET_RPC_URL}"
skale_mainnet = "${SKALE_MAINNET_RPC_URL}"
polygon_mumbai = "${POLYGON_MUMBAI_RPC_URL}"
rsk_testnet = "${RSK_TESTNET_RPC_URL}"
rsk_mainnet = "${RSK_MAINNET_RPC_URL}"

[profile.skale_testnet]
eth_rpc_url = "${SKALE_TESTNET_RPC_URL}"

[profile.skale_mainnet]
eth_rpc_url = "${SKALE_MAINNET_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
